name: Compile

on: pull_request

jobs:
  compilation:
    runs-on: ubuntu-latest
    name: Compilation of the pull request
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Cache the compiler
        uses: actions/cache@v2
        id: cache-compiler
        with:
          path: ~/gcc-arm-none-eabi-9-2020-q2-update
          key: ${{ runner.os }}-gcc-arm-none-eabi-9-2020-q2-update
      - name: Install cross compiler
        if: steps.cache-compiler.outputs.cache-hit != 'true'
        run: |
          cd ~
          curl -O -L https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
          tar xf ./gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
      - name: Install ninja and setup the env
        run: |
          echo "ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb" >> $GITHUB_ENV
          echo "GNUARMEMB_TOOLCHAIN_PATH=~/gcc-arm-none-eabi-9-2020-q2-update" >> $GITHUB_ENV
          echo "~/gcc-arm-none-eabi-9-2020-q2-update/bin" >> $GITHUB_PATH
          sudo apt-get update
          sudo apt-get install ninja-build
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip3 install --user west
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Get nrf connect
        run: |
          cd ..
          west init -m https://github.com/nrfconnect/sdk-nrf --mr v1.4.2 .
          west update
          west zephyr-export
      - name: Install additional python packages
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          pip3 install --user -r ../zephyr/scripts/requirements.txt
          pip3 install --user -r ../nrf/scripts/requirements.txt
          pip3 install --user -r ../bootloader/mcuboot/scripts/requirements.txt
      - name: Compile with west
        run: |
          west build -b nrf5340dk_nrf5340_cpuapp        

